### ISSUE TITLE
Layout Issues

### ISSUE THREAD

**Issue by RiukaSeno** [Valama/valama#124]
I have no idea whether or not anyone else has experienced a similar issue, but it doesn't look like it. Anyway, Valama had been working wonderfully for a while up until recently. When load up a project/start a new project the layout is, for the most part, unresponsive. 

I can interact with the various widgets to an extent and they load correctly, however if I try to dock or resize a widget it does nothing and dragging them around doesn't always work either. 

If I go into the "View" menu and try to enable a widget, it does nothing. If I remove a widget (which I can only do via the "View" menu), I'm unable to get it back.

I've gone and deleted the files wherein Valama's layout and other settings are stored, re-downloaded and compiled again, but the problem persists. 

Any help would be much appreciated. Great work, by the way. Aside from the issues I'm having, I'm really loving the IDE haha. 

(Also, I've not made any major changes to my system and am running a 64-bit installation of Ubuntu 12.04.)

**Comment by LSenf** [comment]
Closing, should be obsolete with valamang anyway
