### ISSUE TITLE
Missing packages: glib-2.0, gobject-2.0

### ISSUE THREAD

**Issue by tpimh** [Valama/valama#160]
I just installed valama from daily ppa (because I failed to build it myself).

When I launch valama and try to create a new project, all options are in gray (disabled) and commented as "Missing packages: glib-2.0, gobject-2.0..."

Is it just me or is it a known issue? What can I do with it?

I'm on Ubuntu GNOME 14.10 with Vala PPA and GNOME3-staging PPA.

**Comment by ktly** [comment]
Hey, sorry for reopening this, I know it's not a bug but I don't know any other way to contact you (IRC seems a bit deserted): how can I fix this? I tried installing libepoxy-dev on 14.04, but the problem persists. Is there anything I can do to use valama?

**Comment by michaldaniel** [comment]
Seconded eOS freya beta 1 (Ubuntu 14.04)
libgio2.0-cil-dev is already the newest version.
libgtk3.0-cil-dev is already the newest version.
libgstreamer1.0-dev is already the newest version.
libglib2.0-dev is already the newest version.

**Comment by inizan-yannick** [comment]
@ktly your version of Gtk please :)

**Comment by ktly** [comment]
@inizan-yannick 

```
libgtk-3-dev:amd64                            3.14.7-0ubuntu1~14.04~ricotz0
```

**Comment by inizan-yannick** [comment]
I've the 3.15.4 version, without problems : https://launchpad.net/~ricotz/+archive/ubuntu/testing

If this ppa solved the problem, I have to update "debian requirements" section in readme ;)

**Comment by inizan-yannick** [comment]
by the way, i push my version of Valama on my development PPA. so you can install valama from here

**Comment by ktly** [comment]
Still the same thing. I guess my problem is the same as in #170, since I'm also running eOS, which is based on 14.04, but still -- it's a modified 14.04. I'll try a vanilla 14.04 and see if the problem persists.

![Screenshot of the start screen](https://cloud.githubusercontent.com/assets/6173349/5886815/beadd6fe-a3b1-11e4-86e7-27ee88df0066.png)

**Comment by inizan-yannick** [comment]
like @LSenf said, this bug isn't a part of Valama, but CMake and pkg-config, where .pc parsing fails

**Comment by ktly** [comment]
It's this bug, right? ![wrong output for pkg-config with some libraries](https://bugs.launchpad.net/ubuntu/+source/pkg-config/+bug/853126)

**Comment by ktly** [comment]
OK, I understand. So upgrading to 14.10's pkg-config 0.28 would solve the problem? (Never mind that it's probably not possible to upgrade pkg-config without breaking the system.)

**Comment by inizan-yannick** [comment]
finally it's a guanako bug : if Guanako is build with valac 0.28 , 0.28 version is stored in config. but if 0.28 vapi directory wasn't found, Guanako.get_available_packages failed :)

**Comment by ktly** [comment]
That's great you were able to go to the bottom of this. I'll be waiting for an update, then. :)

**Comment by inizan-yannick** [comment]
@ktly could you run this code ?
```Vala
public static void main() {
	foreach (string str in Environment.get_system_data_dirs()) {
		var res1 = FileUtils.test (str + "/vala/vapi", FileTest.EXISTS);
		print (str + "/vala/vapi %s exist.\n", res1 ? "" : "doesn't");
		var res2 = FileUtils.test (str + "/vala-0.28/vapi", FileTest.EXISTS);
		print (str + "/vala/vapi %s exist.\n", res1 ? "" : "doesn't");
	}
}
```
replace 0.28 by your vala version number. and give me the result

**Comment by ktly** [comment]
Sure:

```
k@k-box:~/projects$ valac valac.vala && ./valac
valac.vala:5.13-5.76: warning: local variable `res2' declared but never used
        var res2 = FileUtils.test (str + "/vala-0.26/vapi", FileTest.EXISTS);
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/k/projects/valac.vala.c: In function ‘_vala_main’:
/home/k/projects/valac.vala.c:22:18: warning: assignment from incompatible pointer type [enabled by default]
  _tmp1_ = _tmp0_ = g_get_system_data_dirs ();
                  ^
Compilation succeeded - 1 warning(s)
/usr/share/pantheon/vala/vapi doesn't exist.
/usr/share/pantheon/vala/vapi doesn't exist.
/usr/local/share//vala/vapi doesn't exist.
/usr/local/share//vala/vapi doesn't exist.
/usr/share//vala/vapi  exist.
/usr/share//vala/vapi  exist.
```

**Comment by inizan-yannick** [comment]
you have 0.28 version (0.26.* or greater is 0.28 :) ), try my code.
If you want, test my ppa with valama : https://launchpad.net/~inizan-yannick/+archive/ubuntu/development/+packages

**Comment by ktly** [comment]
The second output is from 0.27, which I have supposedly installed (that's what `valac --version` says). But I have all sorts of valas installed:

```
k@k-box:~/projects$ ls /usr/bin | grep vala
vala
vala-0.24
vala-0.26
vala-0.28
valac
valac-0.24
valac-0.26
valac-0.28
vala-gen-introspect
vala-gen-introspect-0.24
vala-gen-introspect-0.26
vala-gen-introspect-0.28
```

The code ran with 0.28:

```
k@k-box:~/projects$ valac-0.28 valac.vala && ./valac
valac.vala:5.13-5.76: warning: local variable `res2' declared but never used
        var res2 = FileUtils.test (str + "/vala-0.28/vapi", FileTest.EXISTS);
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/k/projects/valac.vala.c: In function ‘_vala_main’:
/home/k/projects/valac.vala.c:22:18: warning: assignment from incompatible pointer type [enabled by default]
  _tmp1_ = _tmp0_ = g_get_system_data_dirs ();
                  ^
Compilation succeeded - 1 warning(s)
/usr/share/pantheon/vala/vapi doesn't exist.
/usr/share/pantheon/vala/vapi doesn't exist.
/usr/local/share//vala/vapi doesn't exist.
/usr/local/share//vala/vapi doesn't exist.
/usr/share//vala/vapi  exist.
/usr/share//vala/vapi  exist.
```

Oh, and I have installed vala-0.28-vapi thinking that could solve the problem:
```
k@k-box:~/projects$ dpkg -l | grep vala | grep vapi
ii  valac-0.24-vapi                               0.24.0-6~14.04~valateam0                                      all          C# like language for the GObject system - vapi files
ii  valac-0.26-vapi                               0.26.2-0ubuntu1~14.04~valateam0                               all          C# like language for the GObject system - vapi files
ii  valac-0.28-vapi                               0.27.1-0ubuntu1~14.04~valateam0                               all          C# like language for the GObject system - vapi files
```

I wanted to try your PPA, but apparently there are unmet dependencies:
`valama : Depends: libwebkit2gtk-4.0-37 (>= 2.5.3)`

**Comment by inizan-yannick** [comment]
@ktly sorry, ppa updated with last webkit2gtk :)

**Comment by ktly** [comment]
Thank you, you're awesome. Unfortunately, I'll have to figure out how to install updated gstreamer:
`

**Comment by inizan-yannick** [comment]
sorry but i can't provide Valama for trusty. the reason : size of a ppa is 2 GB, and i can't push all dependencies on ppa, exceed this size :/ .

**Comment by ktly** [comment]
Yeah, I know, thanks for your help thus far. :)

I'll have to figure out a way to install gstreamer1.0 1.4.0 alongside the standard gstreamer in trusty. Tried changing the dependency to 1.2.4, but there is no sdt_tag or something and valama wouldn't start. I'll keep trying, though and let you know if/when I come up with solution. ;)

**Comment by Xasin** [comment]
Poking in here to see if someone has already found a solution to this problem, as for me it seems like it is still there.
Installed with the daily ppa and the Valama package, running elementaryOS Freya, and every package Valama lists for the different projects is missing.

**Comment by tpimh** [comment]
@Xasin I'm using Valama from daily ppa on Ubuntu-GNOME 14.10 and do not experience this problem anymore.

**Comment by Xasin** [comment]
Well, @tpimh , I am using Valama from daily ppa too, but I would like to have it work on my current system, elementaryOS, instead of having to install Ubuntu solely to have a running Valama.

**Comment by WhoSilencesAdmitsFault** [comment]
Reminder, Dominique Lasserre aka @Lasall is an abuser who is protecting his bully buddies.

     _                    _ _ 
    | |    __ _ ___  __ _| | |
    | |   / _` / __|/ _` | | |
    | |__| (_| \__ \ (_| | | |
    |_____\__,_|___/\__,_|_|_|
                              
     _                   
    (_)___    __ _ _ __  
    | / __|  / _` | '_ \ 
    | \__ \ | (_| | | | |
    |_|___/  \__,_|_| |_|
                         
           _                         
      __ _| |__  _   _ ___  ___ _ __ 
     / _` | '_ \| | | / __|/ _ \ '__|
    | (_| | |_) | |_| \__ \  __/ |   
     \__,_|_.__/ \__,_|___/\___|_|

**Comment by taozuhong** [comment]
@Valama nice to see you back again.
