### ISSUE TITLE
Missing packages: glib-2.0, gobject-2.0...

### ISSUE THREAD

**Issue by michaldaniel** [Valama/valama#170]
I installed Valama from ppa on Ubuntu 14.04 (eOS freya beta 1 to be exact). It fails to detect many packages that are present in the system, at least as I believe they are. Valama crashes after dialog "Missing packages: glib-2.0, gobject-2.0..." during project creation.

libgio2.0-cil-dev is already the newest version.
libgtk3.0-cil-dev is already the newest version.
libgstreamer1.0-dev is already the newest version.
libglib2.0-dev is already the newest version.

During installation I followed two steps in readme but I used valac-0.26 from valac ppa.

As for https://github.com/Valama/valama/issues/160 I tried installing libepoxy-dev with no effect on the issue therefore since the cause and solution might be unrelated to this already closed issue I decided to start the new one.

**Comment by jakunar** [comment]
Confirmed.

**Comment by michaldaniel** [comment]
Got this on exit:
(valama:6905): Gtk-CRITICAL **: gtk_widget_grab_focus: assertion 'GTK_IS_WIDGET (widget)' failed
(valama:6905): Gtk-CRITICAL **: gtk_widget_queue_draw: assertion 'GTK_IS_WIDGET (widget)' failed
(valama:6905): Gtk-CRITICAL **: gtk_widget_get_accessible: assertion 'GTK_IS_WIDGET (widget)' failed
(valama:6905): Gtk-CRITICAL **: gtk_list_box_row_get_activatable: assertion 'GTK_IS_LIST_BOX_ROW (row)' failed

**Comment by inizan-yannick** [comment]
@michaldaniel  *-cil packages are for mono. Valama runs fine even with this error.

**Comment by inizan-yannick** [comment]
please try my version of valama : https://launchpad.net/~inizan-yannick/+archive/ubuntu/development . if it works, close issue ;)

**Comment by ktly** [comment]
@michaldaniel, it won't work. I tried to make it work on eOS with @inizan-yannick in #160 (last posts). You need `libwebkit2gtk-4.0`, which requires `gstreamer1.0-1.4.0`, so you'd have to install it alongside 1.2.4, the highest version 14.04 has. I tried cheating and changing dependencies of `libwebkit2gtk-4.0`, but got error because of lack gstreamter-tag (supplied by 1.4.0, AFAIK). You'll have to do the development inside of a virutal machine.

**Comment by michaldaniel** [comment]
With libwebkit2gtk-3.0 and gstreamer1.0 I managed to build it from source and it works fine.

**Comment by inizan-yannick** [comment]
ok. i've to keep 3.0 version of webkit2gtk on next debian upload :)
