### ISSUE TITLE
valamang: Nothing to display

### ISSUE THREAD

**Issue by inizan-yannick** [Valama/valama#176]
nothing is displayed, is this normal?
![capture d ecran_2015-02-16_01-10-19](https://cloud.githubusercontent.com/assets/3141337/6205712/a00a5eba-b578-11e4-9880-952c30b79330.png)

**Comment by LSenf** [comment]
Oops, sry, should have mentioned that: currently, you have to press enter to show an editor.
Thanks to GtkListBox -.-
So far I haven't found a way to get the activate signal for a row on a single click... Maybe I will change it to use the selection signal of the listbox.
If anyone knows a simple solution, the code is in src/ui/project_structure.vala
Good to see you can get it to run though :)

**Comment by LSenf** [comment]
Should be fixed now, was easier than i thought :)

**Comment by inizan-yannick** [comment]
How to capture 'clicked' signal ? Create a custom listboxrow with an unique id. On listbox activate signal, cast current row as your custom row and check id :) (other solution is to check title of current row)
