### ISSUE TITLE
Build Error: `GuanakoCompletion.get_start_iter' is incompatible with base method `Gtk.SourceCompletionProvider.get_start_iter': incompatible direction of parameter 3.

### ISSUE THREAD

**Issue by neumann89** [Valama/valama#181]
I had to change to the method header to get it built in completion_provider.c:227 : 

`public bool get_start_iter (Gtk.SourceCompletionContext context,
                                Gtk.SourceCompletionProposal proposal,
                                out Gtk.TextIter iter)
`

Parameter **Gtk.TextIter iter** was not **out** before.

**Comment by neumann89** [comment]
My system: Archlinux 64bit

**Comment by inizan-yannick** [comment]
What's your version of GtkSourceView ?

**Comment by neumann89** [comment]
3.14.3

**Comment by inizan-yannick** [comment]
hum ok, GtkSV team have updated vapi. by the way, this function is unused in Valama and must be removed from source :)

**Comment by inizan-yannick** [comment]
@neumann89 pull requested ;)

**Comment by neumann89** [comment]
fixed by #188 and #187
