### ISSUE TITLE
Waf support

### ISSUE THREAD

**Issue by neumann89** [Valama/valama#182]
Support for a next generation build-system like Waf would be awesome :)

**Comment by LSenf** [comment]
This will be relatively easy to achieve for valamang. The buildsystem code is not ready yet, but it wont take long.
I have to focus on more essential work now, but I would be glad to include it if you could contribute the code :)

**Comment by LSenf** [comment]
valamang is ready for buildsystem backends now :)

**Comment by LSenf** [comment]
I just committed a waf script in a separate data dir for builders.
I also added a target "waftest" for testing.

When building via valama, the script can be found at _Config.DATA_DIR + "/builder/Waf/waf"_.
build.sh does not support data dirs (it's time we get a working stand-alone buildsystem :) )

**Comment by neumann89** [comment]
Nice :+1:
