### ISSUE TITLE
valamang: can't resize panels, work with source code is very difficult.

### ISSUE THREAD

**Issue by rastersoft** [Valama/valama#192]
I updated the repository and recompiled valamang, and found that I can't resize the panels with the source code, the files, the terminal... the size for the source code panel is quite small, so trying to work with it is very difficult. I think it worked previously...

**Comment by LSenf** [comment]
In valamang I just added resizable panes. You are welcome to commit adjustments to the UI file it is now using :) (MainWidget.glade)

**Comment by rastersoft** [comment]
It seems you forgot to add src/ui/MainWidget.glade to the repository :(

**Comment by LSenf** [comment]
Whoops, added it :)

**Comment by rastersoft** [comment]
Thanks, now it builds fine.
