### ISSUE TITLE
valamang: Convert project templates to new format

### ISSUE THREAD

**Issue by LSenf** [Valama/valama#200]
The project templates (valamang/templates/) format has changed slightly, especially the old .vlp project files need to be updated.
You can use the "plain vala" template (converted already) as a reference, as well as any valamang project file.
In the end, all templates should be usable and produce working projects that can be compiled and executed

**Comment by inizan-yannick** [comment]
Hi, i work on this issue (gstreamer templates already updated at this time)

**Comment by inizan-yannick** [comment]
I have to modify some files in code for library building

**Comment by inizan-yannick** [comment]
You can close this feature now :)

**Comment by LSenf** [comment]
Solved by @inizan-yannick , thanks :)
