### ISSUE TITLE
Cant build on fedora 22, got error on make.

### ISSUE THREAD

**Issue by firefixmaarten** [Valama/valama#206]
/usr/bin/cmake -H/home/maarten/GIT/valama -B/home/maarten/GIT/valama/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/maarten/GIT/valama/build/CMakeFiles /home/maarten/GIT/valama/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/maarten/GIT/valama/build'
make -f CMakeFiles/ui_copy_valama.dir/build.make CMakeFiles/ui_copy_valama.dir/depend
make -f guanako/CMakeFiles/ui_copy_guanako.dir/build.make guanako/CMakeFiles/ui_copy_guanako.dir/depend
make -f CMakeFiles/gsettings_valama.dir/build.make CMakeFiles/gsettings_valama.dir/depend
make -f icons/CMakeFiles/icons.dir/build.make icons/CMakeFiles/icons.dir/depend
make -f icons/CMakeFiles/icons_text.dir/build.make icons/CMakeFiles/icons_text.dir/depend
make[2]: Entering directory '/home/maarten/GIT/valama/build'
make[2]: Entering directory '/home/maarten/GIT/valama/build'
cd /home/maarten/GIT/valama/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/maarten/GIT/valama /home/maarten/GIT/valama /home/maarten/GIT/valama/build /home/maarten/GIT/valama/build /home/maarten/GIT/valama/build/CMakeFiles/gsettings_valama.dir/DependInfo.cmake --color=
make[2]: Entering directory '/home/maarten/GIT/valama/build'
cd /home/maarten/GIT/valama/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/maarten/GIT/valama /home/maarten/GIT/valama /home/maarten/GIT/valama/build /home/maarten/GIT/valama/build /home/maarten/GIT/valama/build/CMakeFiles/ui_copy_valama.dir/DependInfo.cmake --color=
make[2]: Entering directory '/home/maarten/GIT/valama/build'
make[2]: Entering directory '/home/maarten/GIT/valama/build'
make[2]: Leaving directory '/home/maarten/GIT/valama/build'
make[2]: Leaving directory '/home/maarten/GIT/valama/build'
make[2]: Leaving directory '/home/maarten/GIT/valama/build'
make -f icons/CMakeFiles/icons_text.dir/build.make icons/CMakeFiles/icons_text.dir/build
make -f CMakeFiles/ui_copy_valama.dir/build.make CMakeFiles/ui_copy_valama.dir/build
make -f CMakeFiles/gsettings_valama.dir/build.make CMakeFiles/gsettings_valama.dir/build
make[2]: Leaving directory '/home/maarten/GIT/valama/build'
make[2]: Entering directory '/home/maarten/GIT/valama/build'
make[2]: Nothing to be done for 'CMakeFiles/ui_copy_valama.dir/build'.
make[2]: Leaving directory '/home/maarten/GIT/valama/build'
make -f icons/CMakeFiles/icons.dir/build.make icons/CMakeFiles/icons.dir/build
/usr/bin/cmake -E cmake_progress_report /home/maarten/GIT/valama/build/CMakeFiles 
make[2]: Entering directory '/home/maarten/GIT/valama/build'
make[2]: Entering directory '/home/maarten/GIT/valama/build'
make[2]: Nothing to be done for 'CMakeFiles/gsettings_valama.dir/build'.
make[2]: Leaving directory '/home/maarten/GIT/valama/build'
/usr/bin/cmake -E cmake_progress_report /home/maarten/GIT/valama/build/CMakeFiles  7 8
make[2]: Entering directory '/home/maarten/GIT/valama/build'
[  0%] [  1%] make[2]: Leaving directory '/home/maarten/GIT/valama/build'
make -f guanako/CMakeFiles/ui_copy_guanako.dir/build.make guanako/CMakeFiles/ui_copy_guanako.dir/build
Built target ui_copy_valama
make -f po/CMakeFiles/translations.dir/build.make po/CMakeFiles/translations.dir/depend
[  2%] /usr/bin/cmake -E cmake_progress_report /home/maarten/GIT/valama/build/CMakeFiles 
[  4%] Generate application icons.
Built target gsettings_valama
make -f tests/CMakeFiles/copy_datafiles.dir/build.make tests/CMakeFiles/copy_datafiles.dir/depend
make[2]: Leaving directory '/home/maarten/GIT/valama/build'
/usr/bin/cmake -E cmake_progress_report /home/maarten/GIT/valama/build/CMakeFiles  20 21 22 23 24 25 26 27 28
make[2]: Entering directory '/home/maarten/GIT/valama/build'
make[2]: Entering directory '/home/maarten/GIT/valama/build'
[  4%] Generate text logo.
Built target ui_copy_guanako
make[2]: Leaving directory '/home/maarten/GIT/valama/build'
make -f guanako/CMakeFiles/guanako.dir/build.make guanako/CMakeFiles/guanako.dir/depend
/usr/bin/cmake -E cmake_progress_report /home/maarten/GIT/valama/build/CMakeFiles  29 30
[ 13%] make[2]: Entering directory '/home/maarten/GIT/valama/build'
[ 14%] make[2]: Leaving directory '/home/maarten/GIT/valama/build'
make -f tests/CMakeFiles/copy_datafiles.dir/build.make tests/CMakeFiles/copy_datafiles.dir/build
make[2]: Leaving directory '/home/maarten/GIT/valama/build'
make -f po/CMakeFiles/translations.dir/build.make po/CMakeFiles/translations.dir/build
Built target icons
Built target icons_text
/usr/bin/cmake -E cmake_progress_report /home/maarten/GIT/valama/build/CMakeFiles  1 2 3 4 5 6
make[2]: Entering directory '/home/maarten/GIT/valama/build'
[ 20%] make[2]: Leaving directory '/home/maarten/GIT/valama/build'
make -f guanako/CMakeFiles/guanako.dir/build.make guanako/CMakeFiles/guanako.dir/build
[ 21%] Built target copy_datafiles
/usr/bin/cmake -E cmake_progress_report /home/maarten/GIT/valama/build/CMakeFiles  9 10 11 12 13 14 15 16 17 18 19
Build translations.
[ 34%] make[2]: Leaving directory '/home/maarten/GIT/valama/build'
/usr/bin/cmake -E cmake_progress_report /home/maarten/GIT/valama/build/CMakeFiles  51 52 53 54 55 56
Built target guanako
make -f CMakeFiles/valama.dir/build.make CMakeFiles/valama.dir/depend
[ 39%] make[2]: Entering directory '/home/maarten/GIT/valama/build'
/usr/bin/cmake -E cmake_progress_report /home/maarten/GIT/valama/build/CMakeFiles 57
Built target translations
[ 40%] Generating src/buildsystem/autotools.c, src/buildsystem/base.c, src/buildsystem/buildsystem_template.c, src/buildsystem/cmake.c, src/buildsystem/plain.c, src/common/args.c, src/common/common.c, src/common/ui_helpers.c, src/completion_provider.c, src/dialogs/about.c, src/dialogs/create_file.c, src/dialogs/missing_packages.c, src/dialogs/project_settings.c, src/main.c, src/project/build_project.c, src/project/package_management.c, src/project/project.c, src/project/project_file.c, src/project/project_templates.c, src/settings.c, src/ui/app_output.c, src/ui/breakpoints.c, src/ui/build_output.c, src/ui/current_file_structure.c, src/ui/glade_viewer.c, src/ui/project_browser.c, src/ui/reports.c, src/ui/search.c, src/ui/source_viewer.c, src/ui/structure_view.c, src/ui/super_source_view.c, src/ui/symbol_browser.c, src/ui/ui_elements.c, src/ui/valadoc_browser.c, src/ui/welcome_screen.c, src/ui/welcome_screen/create_project_buildsystem.c, src/ui/welcome_screen/create_project_location.c, src/ui/welcome_screen/create_project_packages.c, src/ui/welcome_screen/create_project_template.c, src/ui/welcome_screen/load_project.c, src/ui/welcome_screen/main_screen.c, src/ui/widgets/browser_path.c, src/ui_main.c
/usr/bin/valac -C -b /home/maarten/GIT/valama -d /home/maarten/GIT/valama/build --pkg=atk --pkg=cairo --pkg=clutter-1.0 --pkg=clutter-gtk-1.0 --pkg=cogl-1.0 --pkg=gdk-3.0 --pkg=gdk-pixbuf-2.0 --pkg=gdl-3.0 --pkg=gee-0.8 --pkg=gio-2.0 --pkg=glib-2.0 --pkg=gmodule-2.0 --pkg=gobject-2.0 --pkg=gtk+-3.0 --pkg=gtksourceview-3.0 --pkg=json-glib-1.0 --pkg=libsoup-2.4 --pkg=libvala-0.28 --pkg=libxml-2.0 --pkg=pango --pkg=pangocairo --pkg=posix --pkg=x11 --pkg=webkit2gtk-4.0 --define=UNIX --define=VALAC_0_26 --define=GTK_SOURCE_VIEW_3_14_3 --define=GDL_3_9_91 --define=WEBKIT2_GTK_4.0 --thread --target-glib 2.44.0 --enable-experimental --fatal-warnings --vapidir=/home/maarten/GIT/valama/extravapi/gdl-3.0 /home/maarten/GIT/valama/src/buildsystem/autotools.vala /home/maarten/GIT/valama/src/buildsystem/base.vala /home/maarten/GIT/valama/src/buildsystem/buildsystem_template.vala /home/maarten/GIT/valama/src/buildsystem/cmake.vala /home/maarten/GIT/valama/src/buildsystem/plain.vala /home/maarten/GIT/valama/src/common/args.vala /home/maarten/GIT/valama/src/common/common.vala /home/maarten/GIT/valama/src/common/ui_helpers.vala /home/maarten/GIT/valama/src/completion_provider.vala /home/maarten/GIT/valama/src/dialogs/about.vala /home/maarten/GIT/valama/src/dialogs/create_file.vala /home/maarten/GIT/valama/src/dialogs/missing_packages.vala /home/maarten/GIT/valama/src/dialogs/project_settings.vala /home/maarten/GIT/valama/src/main.vala /home/maarten/GIT/valama/src/project/build_project.vala /home/maarten/GIT/valama/src/project/package_management.vala /home/maarten/GIT/valama/src/project/project.vala /home/maarten/GIT/valama/src/project/project_file.vala /home/maarten/GIT/valama/src/project/project_templates.vala /home/maarten/GIT/valama/src/settings.vala /home/maarten/GIT/valama/src/ui/app_output.vala /home/maarten/GIT/valama/src/ui/breakpoints.vala /home/maarten/GIT/valama/src/ui/build_output.vala /home/maarten/GIT/valama/src/ui/current_file_structure.vala /home/maarten/GIT/valama/src/ui/glade_viewer.vala /home/maarten/GIT/valama/src/ui/project_browser.vala /home/maarten/GIT/valama/src/ui/reports.vala /home/maarten/GIT/valama/src/ui/search.vala /home/maarten/GIT/valama/src/ui/source_viewer.vala /home/maarten/GIT/valama/src/ui/structure_view.vala /home/maarten/GIT/valama/src/ui/super_source_view.vala /home/maarten/GIT/valama/src/ui/symbol_browser.vala /home/maarten/GIT/valama/src/ui/ui_elements.vala /home/maarten/GIT/valama/src/ui/valadoc_browser.vala /home/maarten/GIT/valama/src/ui/welcome_screen.vala /home/maarten/GIT/valama/src/ui/welcome_screen/create_project_buildsystem.vala /home/maarten/GIT/valama/src/ui/welcome_screen/create_project_location.vala /home/maarten/GIT/valama/src/ui/welcome_screen/create_project_packages.vala /home/maarten/GIT/valama/src/ui/welcome_screen/create_project_template.vala /home/maarten/GIT/valama/src/ui/welcome_screen/load_project.vala /home/maarten/GIT/valama/src/ui/welcome_screen/main_screen.vala /home/maarten/GIT/valama/src/ui/widgets/browser_path.vala /home/maarten/GIT/valama/src/ui_main.vala /home/maarten/GIT/valama/vapi/config.vapi /home/maarten/GIT/valama/vapi/gladeui-2.0.vapi /home/maarten/GIT/valama/build/guanako/guanako.vapi
/home/maarten/GIT/valama/src/ui/structure_view.vala:224.21-224.44: warning: Clutter.Rectangle.new has been deprecated since 1.10
Compilation failed: 0 error(s), 1 warning(s)
CMakeFiles/valama.dir/build.make:229: recipe for target 'vala.stamp' failed
make[2]: *** [vala.stamp] Error 1
make[2]: Leaving directory '/home/maarten/GIT/valama/build'
CMakeFiles/Makefile2:158: recipe for target 'CMakeFiles/valama.dir/all' failed
make[1]: *** [CMakeFiles/valama.dir/all] Error 2
make[1]: Leaving directory '/home/maarten/GIT/valama/build'
Makefile:119: recipe for target 'all' failed
make: *** [all] Error 2

Any help is welcome. I am looking for a good IDE for vala.

**Comment by inizan-yannick** [comment]
please see my pull request : https://github.com/Valama/valama/pull/205
updated with latest vapi

**Comment by LSenf** [comment]
Merged the pull request, please reopen in case of further problems :)

**Comment by firefixmaarten** [comment]
Got a new error, btw dualbooting with archlinux to, same problem there.

/usr/bin/cmake -H/home/maarten/GIT/valama -B/home/maarten/GIT/valama/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/maarten/GIT/valama/build/CMakeFiles /home/maarten/GIT/valama/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Map '/home/maarten/GIT/valama/build' wordt binnengegaan
make -f CMakeFiles/gsettings_valama.dir/build.make CMakeFiles/gsettings_valama.dir/depend
make -f guanako/CMakeFiles/ui_copy_guanako.dir/build.make guanako/CMakeFiles/ui_copy_guanako.dir/depend
make -f CMakeFiles/ui_copy_valama.dir/build.make CMakeFiles/ui_copy_valama.dir/depend
make -f icons/CMakeFiles/icons.dir/build.make icons/CMakeFiles/icons.dir/depend
make -f icons/CMakeFiles/icons_text.dir/build.make icons/CMakeFiles/icons_text.dir/depend
make[2]: Map '/home/maarten/GIT/valama/build' wordt binnengegaan
make[2]: Map '/home/maarten/GIT/valama/build' wordt binnengegaan
cd /home/maarten/GIT/valama/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/maarten/GIT/valama /home/maarten/GIT/valama /home/maarten/GIT/valama/build /home/maarten/GIT/valama/build /home/maarten/GIT/valama/build/CMakeFiles/gsettings_valama.dir/DependInfo.cmake --color=
make[2]: Map '/home/maarten/GIT/valama/build' wordt binnengegaan
cd /home/maarten/GIT/valama/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/maarten/GIT/valama /home/maarten/GIT/valama /home/maarten/GIT/valama/build /home/maarten/GIT/valama/build /home/maarten/GIT/valama/build/CMakeFiles/ui_copy_valama.dir/DependInfo.cmake --color=
make[2]: Map '/home/maarten/GIT/valama/build' wordt binnengegaan
make[2]: Map '/home/maarten/GIT/valama/build' wordt binnengegaan
make[2]: Map '/home/maarten/GIT/valama/build' wordt verlaten
make -f guanako/CMakeFiles/ui_copy_guanako.dir/build.make guanako/CMakeFiles/ui_copy_guanako.dir/build
make[2]: Map '/home/maarten/GIT/valama/build' wordt verlaten
make -f CMakeFiles/gsettings_valama.dir/build.make CMakeFiles/gsettings_valama.dir/build
make[2]: Map '/home/maarten/GIT/valama/build' wordt verlaten
make[2]: Map '/home/maarten/GIT/valama/build' wordt verlaten
make -f CMakeFiles/ui_copy_valama.dir/build.make CMakeFiles/ui_copy_valama.dir/build
make -f icons/CMakeFiles/icons_text.dir/build.make icons/CMakeFiles/icons_text.dir/build
make[2]: Map '/home/maarten/GIT/valama/build' wordt binnengegaan
make[2]: Er hoeft niets gedaan te worden voor 'CMakeFiles/gsettings_valama.dir/build'.
make[2]: Map '/home/maarten/GIT/valama/build' wordt verlaten
/usr/bin/cmake -E cmake_progress_report /home/maarten/GIT/valama/build/CMakeFiles  7 8
/usr/bin/cmake -E cmake_progress_report /home/maarten/GIT/valama/build/CMakeFiles 
make[2]: Map '/home/maarten/GIT/valama/build' wordt binnengegaan
make[2]: Map '/home/maarten/GIT/valama/build' wordt binnengegaan
make[2]: Er hoeft niets gedaan te worden voor 'CMakeFiles/ui_copy_valama.dir/build'.
make[2]: Map '/home/maarten/GIT/valama/build' wordt verlaten
/usr/bin/cmake -E cmake_progress_report /home/maarten/GIT/valama/build/CMakeFiles 
make[2]: Map '/home/maarten/GIT/valama/build' wordt verlaten
make -f icons/CMakeFiles/icons.dir/build.make icons/CMakeFiles/icons.dir/build
[  2%] [  3%] make[2]: Map '/home/maarten/GIT/valama/build' wordt binnengegaan
[  3%] Built target gsettings_valama
make -f po/CMakeFiles/translations.dir/build.make po/CMakeFiles/translations.dir/depend
[  3%] Built target ui_copy_valama
make[2]: Map '/home/maarten/GIT/valama/build' wordt binnengegaan
make -f tests/CMakeFiles/copy_datafiles.dir/build.make tests/CMakeFiles/copy_datafiles.dir/depend
make[2]: Map '/home/maarten/GIT/valama/build' wordt binnengegaan
[  4%] Built target ui_copy_guanako
make -f guanako/CMakeFiles/guanako.dir/build.make guanako/CMakeFiles/guanako.dir/depend
Generate text logo.
make[2]: Map '/home/maarten/GIT/valama/build' wordt verlaten
/usr/bin/cmake -E cmake_progress_report /home/maarten/GIT/valama/build/CMakeFiles  29 30
make[2]: Map '/home/maarten/GIT/valama/build' wordt binnengegaan
make[2]: Map '/home/maarten/GIT/valama/build' wordt verlaten
make -f po/CMakeFiles/translations.dir/build.make po/CMakeFiles/translations.dir/build
Generate application icons.
[  5%] make[2]: Map '/home/maarten/GIT/valama/build' wordt verlaten
/usr/bin/cmake -E cmake_progress_report /home/maarten/GIT/valama/build/CMakeFiles  20 21 22 23 24 25 26 27 28
make[2]: Map '/home/maarten/GIT/valama/build' wordt binnengegaan
make[2]: Map '/home/maarten/GIT/valama/build' wordt verlaten
make -f guanako/CMakeFiles/guanako.dir/build.make guanako/CMakeFiles/guanako.dir/build
/usr/bin/cmake -E cmake_progress_report /home/maarten/GIT/valama/build/CMakeFiles  9 10 11 12 13 14 15 16 17 18 19
make[2]: Map '/home/maarten/GIT/valama/build' wordt verlaten
[  9%] make -f tests/CMakeFiles/copy_datafiles.dir/build.make tests/CMakeFiles/copy_datafiles.dir/build
[ 15%] Built target icons_text
/usr/bin/cmake -E cmake_progress_report /home/maarten/GIT/valama/build/CMakeFiles  1 2 3 4 5 6
Built target icons
[ 27%] [ 34%] Built target guanako
make -f CMakeFiles/valama.dir/build.make CMakeFiles/valama.dir/depend
Build translations.
Built target copy_datafiles
make[2]: Map '/home/maarten/GIT/valama/build' wordt verlaten
/usr/bin/cmake -E cmake_progress_report /home/maarten/GIT/valama/build/CMakeFiles  51 52 53 54 55 56
make[2]: Map '/home/maarten/GIT/valama/build' wordt binnengegaan
cd /home/maarten/GIT/valama/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/maarten/GIT/valama /home/maarten/GIT/valama /home/maarten/GIT/valama/build /home/maarten/GIT/valama/build /home/maarten/GIT/valama/build/CMakeFiles/valama.dir/DependInfo.cmake --color=
[ 39%] Built target translations
make[2]: Map '/home/maarten/GIT/valama/build' wordt verlaten
make -f CMakeFiles/valama.dir/build.make CMakeFiles/valama.dir/build
make[2]: Map '/home/maarten/GIT/valama/build' wordt binnengegaan
Linking C executable valama
/usr/bin/cmake -E cmake_link_script CMakeFiles/valama.dir/link.txt --verbose=1
/usr/bin/cc     CMakeFiles/valama.dir/src/buildsystem/autotools.c.o CMakeFiles/valama.dir/src/buildsystem/base.c.o CMakeFiles/valama.dir/src/buildsystem/buildsystem_template.c.o CMakeFiles/valama.dir/src/buildsystem/cmake.c.o CMakeFiles/valama.dir/src/buildsystem/plain.c.o CMakeFiles/valama.dir/src/common/args.c.o CMakeFiles/valama.dir/src/common/common.c.o CMakeFiles/valama.dir/src/common/ui_helpers.c.o CMakeFiles/valama.dir/src/completion_provider.c.o CMakeFiles/valama.dir/src/dialogs/about.c.o CMakeFiles/valama.dir/src/dialogs/create_file.c.o CMakeFiles/valama.dir/src/dialogs/missing_packages.c.o CMakeFiles/valama.dir/src/dialogs/project_settings.c.o CMakeFiles/valama.dir/src/main.c.o CMakeFiles/valama.dir/src/project/build_project.c.o CMakeFiles/valama.dir/src/project/package_management.c.o CMakeFiles/valama.dir/src/project/project.c.o CMakeFiles/valama.dir/src/project/project_file.c.o CMakeFiles/valama.dir/src/project/project_templates.c.o CMakeFiles/valama.dir/src/settings.c.o CMakeFiles/valama.dir/src/ui/app_output.c.o CMakeFiles/valama.dir/src/ui/breakpoints.c.o CMakeFiles/valama.dir/src/ui/build_output.c.o CMakeFiles/valama.dir/src/ui/current_file_structure.c.o CMakeFiles/valama.dir/src/ui/glade_viewer.c.o CMakeFiles/valama.dir/src/ui/project_browser.c.o CMakeFiles/valama.dir/src/ui/reports.c.o CMakeFiles/valama.dir/src/ui/search.c.o CMakeFiles/valama.dir/src/ui/source_viewer.c.o CMakeFiles/valama.dir/src/ui/structure_view.c.o CMakeFiles/valama.dir/src/ui/super_source_view.c.o CMakeFiles/valama.dir/src/ui/symbol_browser.c.o CMakeFiles/valama.dir/src/ui/ui_elements.c.o CMakeFiles/valama.dir/src/ui/valadoc_browser.c.o CMakeFiles/valama.dir/src/ui/welcome_screen.c.o CMakeFiles/valama.dir/src/ui/welcome_screen/create_project_buildsystem.c.o CMakeFiles/valama.dir/src/ui/welcome_screen/create_project_location.c.o CMakeFiles/valama.dir/src/ui/welcome_screen/create_project_packages.c.o CMakeFiles/valama.dir/src/ui/welcome_screen/create_project_template.c.o CMakeFiles/valama.dir/src/ui/welcome_screen/load_project.c.o CMakeFiles/valama.dir/src/ui/welcome_screen/main_screen.c.o CMakeFiles/valama.dir/src/ui/widgets/browser_path.c.o CMakeFiles/valama.dir/src/ui_main.c.o  -o valama -rdynamic -lclutter-gtk-1.0 -lclutter-1.0 -lcogl-path -lcogl-pango -lcogl -lgmodule-2.0 -pthread -lwayland-egl -lgbm -ldrm -lEGL -lXrandr -ljson-glib-1.0 -lwayland-cursor -lwayland-client -lxkbcommon -lwayland-server -lX11 -lXext -lXdamage -lXfixes -lXcomposite -lXi -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lgdk_pixbuf-2.0 -lcairo-gobject -lcairo -lgobject-2.0 -lglib-2.0 -lgdl-3 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lgee-0.8 -lgobject-2.0 -lglib-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lglib-2.0 -lgobject-2.0 -lglib-2.0 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lgtksourceview-3.0 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lvala-0.28 -lgobject-2.0 -lglib-2.0 -lxml2 -lwebkit2gtk-4.0 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lsoup-2.4 -lgio-2.0 -lgobject-2.0 -ljavascriptcoregtk-4.0 -lglib-2.0 -lgthread-2.0 -pthread -lglib-2.0 -lgladeui-2 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lxml2 -lm guanako/libguanako.so.1.0 -lgdl-3 -lgtksourceview-3.0 -lwebkit2gtk-4.0 -lsoup-2.4 -ljavascriptcoregtk-4.0 -lgladeui-2 -lm -pthread -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lgee-0.8 -lvala-0.28 -lxml2 -lgthread-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lgee-0.8 -lvala-0.28 -lxml2 -lgthread-2.0 -Wl,-rpath,/home/maarten/GIT/valama/build/guanako: 
CMakeFiles/valama.dir/src/common/args.c.o: In function `args_parse':
args.c:(.text+0x135): undefined reference to `g_option_context_unref'
args.c:(.text+0x2dd): undefined reference to `g_option_context_unref'
args.c:(.text+0x316): undefined reference to `g_option_context_unref'
args.c:(.text+0x3db): undefined reference to `g_option_context_unref'
collect2: fout: ld gaf exit-status 1 terug
CMakeFiles/valama.dir/build.make:1318: recept voor doel 'valama' is mislukt
make[2]: *** [valama] Fout 1
make[2]: Map '/home/maarten/GIT/valama/build' wordt verlaten
CMakeFiles/Makefile2:158: recept voor doel 'CMakeFiles/valama.dir/all' is mislukt
make[1]: *** [CMakeFiles/valama.dir/all] Fout 2
make[1]: Map '/home/maarten/GIT/valama/build' wordt verlaten
Makefile:119: recept voor doel 'all' is mislukt
make: *** [all] Fout 2

**Comment by inizan-yannick** [comment]
this error is due to wrong vapi in latest vala (GLIB_2_44 directive in wrong place), not a Valama error :)
