### ISSUE TITLE
gedit plugin isn't in gedit

### ISSUE THREAD

**Issue by bb010g** [Valama/valama#208]
I installed the `gedit_plugin` (which I would reccomend renaming to `autovala_gedit_plugin`) through pacman, but it's not showing up in gedit. Arch 64 bit.

**Comment by LSenf** [comment]
erm, we only have a gedit plugin for editing completion defenitions for valama (which you only need if you want to improve valama's autocompletion). I guess you are confusing valama with a vala plugin for gedit; if this is really related to valama, please reopen :)

**Comment by bb010g** [comment]
Sorry, meant this for rastersoft/autovala. My bad. :)
