### ISSUE TITLE
Can't build ( ARCH x64 )

### ISSUE THREAD

**Issue by Ogromny** [Valama/valama#209]
Hi,
When i `make -j2`, i get:
```
 ...
CMakeFiles/valama.dir/src/common/args.c.o: dans la fonction « args_parse »:
args.c:(.text+0x135): référence indéfinie vers « g_option_context_unref »
args.c:(.text+0x2dd): référence indéfinie vers « g_option_context_unref »
args.c:(.text+0x316): référence indéfinie vers « g_option_context_unref »
args.c:(.text+0x3db): référence indéfinie vers « g_option_context_unref »
collect2: erreur: ld a retourné 1 code d'état d'exécution
...
```

PS: I'm french :D

**Comment by inizan-yannick** [comment]
bug connu mais venant de vala, où les développeurs ont défini une mauvaise version de GLib pour le code C :
known bug but from vala, where developers have set wrong define for GLib in CCode :

```
#if GLIB_2_44
	[CCode (ref_function = "g_option_context_ref", unref_function = "g_option_context_unref", type_id = "G_TYPE_OPTION_GROUP")]
#else
	[CCode (free_function = "g_option_context_free")]
#endif
```
dans CMakeLists.txt, change la ligne "--target-glib" avec celle ci :
in CMakeLists.txt, replace '--target-glib' line with this one :
"--target-glib" "2.32"

**Comment by inizan-yannick** [comment]
p.s. : pour les utilisateurs francophones, ils n'ont qu'à venir me voir sur twitter @breizhodrome ;)

**Comment by Ogromny** [comment]
Merci beaucoup de m'avoir répondue aussi vite :D
Thanks you, for your response :D

**Comment by inizan-yannick** [comment]
Fixé :) : https://github.com/inizan-yannick/valama/commit/7a17e8beb428a306882a4041b68e9fcc455cd486

**Comment by inizan-yannick** [comment]
![capture d ecran_2015-06-16_10-05-29](https://cloud.githubusercontent.com/assets/3141337/8178576/93a8dd2c-140f-11e5-8ced-a88a564e02b7.png)

Ce matin dans les mails. l'erreur va être corrigée ^^

**Comment by inizan-yannick** [comment]
solved in latest Vala commit / résolu dans le dernier commit Vala : https://git.gnome.org/browse/vala/commit/?id=e6b24a2e5f00ba73dd06b8e57cc1ab8ccddf38ee

**Comment by LSenf** [comment]
So I guess this is solved, please reopen if necessary
