### ISSUE TITLE
Add gitter chan

### ISSUE THREAD

**Issue by inizan-yannick** [Valama/valama#214]
Add gitter chat functionality to repository may be a good idea

**Comment by LSenf** [comment]
Sounds pretty good! I'll look into that

**Comment by LSenf** [comment]
https://gitter.im/Valama?utm_source=share-link&utm_medium=link&utm_campaign=share-link
Should be public, can you join it?

**Comment by inizan-yannick** [comment]
No :/

![capture d ecran_2015-06-30_16-27-24](https://cloud.githubusercontent.com/assets/3141337/8433250/ef44a054-1f44-11e5-95ea-277da7ba3b2c.png)

**Comment by LSenf** [comment]
I think it works now... Please reopen if i screwed up again ^^
