### ISSUE TITLE
How can I add packages to valama?

### ISSUE THREAD

**Issue by RdlP** [Valama/valama#215]
Hello,

I want to use mysql module in vala program, if I list my vapi directory (/usr/share/vala/vapi) I can see

```
mysql.vapi
```
I installed the sources via:

```
sudo apt-get install libmysqlclient-dev
```
and when I execute the next command:

```
sudo find / -name "mysql.h"
```

I get

```
/usr/include/mysql/mysql.h
```

But when I do double click over package menu in valama it doesn't show me a mysql package.

I have Ubuntu-gnome.

**Comment by inizan-yannick** [comment]
hum yes, we can't add custom flags on project (-X -lmysqlclient) . I work on this feature :)

**Comment by inizan-yannick** [comment]
if you want try my last commit :)

![capture d ecran_2015-06-19_10-23-56](https://cloud.githubusercontent.com/assets/3141337/8249706/51fb0dea-166d-11e5-9655-a41af235a488.png)

![capture d ecran_2015-06-19_10-25-11](https://cloud.githubusercontent.com/assets/3141337/8249734/80fa0966-166d-11e5-8423-9bfdddc73244.png)
