### ISSUE TITLE
[Feature] Multi projects support

### ISSUE THREAD

**Issue by inizan-yannick** [Valama/valama#218]
I work on multi projects support, like Visual Studio / MonoDevelop solutions. Any advices / ideas are welcome ^^

**Comment by LSenf** [comment]
valamang already supports this to some degree, as you can specify different source files for each target. Hopefully good enough for most use cases? :)
I think for now, there are some more important things like testing / completing the CMake buildsystem backend...

**Comment by inizan-yannick** [comment]
already supported in valamang, good ^^
