### ISSUE TITLE
How about to add the ide settings?

### ISSUE THREAD

**Issue by alsoijw** [Valama/valama#220]
Color syntax highlighting is not pleasant. Where is the code that determines these colors?

**Comment by inizan-yannick** [comment]
It's LineAnnotation, the code is here : https://github.com/Valama/valama/blob/master/src/ui/super_source_view.vala

**Comment by alsoijw** [comment]
[I found the following files that use the class LineAnnotation](https://github.com/Valama/valama/search?utf8=%E2%9C%93&q=LineAnnotation). I change src/ui/source_viewer.vala.
Before:
![2015-07-09 14 14 08](https://cloud.githubusercontent.com/assets/8123624/8596522/974043d4-2658-11e5-838d-2f0bfee21391.png)
After:
![2015-07-09 15 35 36](https://cloud.githubusercontent.com/assets/8123624/8596524/9a747688-2658-11e5-8291-8fc0f5605a78.png)
Yet the question remains. How to change the colors of the syntax highlighting?

**Comment by LSenf** [comment]
the highlighting is already done by the GtkSourceView, we don't do that ourselves. What you found is an extension of it to additionally support the floating texts you show in your screenshot.

You can find a documentation of gtksourceview here:
http://valadoc.org/#!api=gtksourceview-3.0/Gtk.SourceView
It should be possible to change the color scheme somewhere there... I don't see it at first glance though. You can probably take other projects for reference on how to achieve that

**Comment by inizan-yannick** [comment]
you can set color scheme in source buffer

**Comment by alsoijw** [comment]
I found where to insert the code. Valama can use the same color scheme that gedit. I think you need to implement the saving of the selected scheme in dconf. As I understand I need to fork Valama to add my changes

**Comment by LSenf** [comment]
Sounds good; github has some good tutorials on forking / pull requests etc, e.g.

https://help.github.com/articles/using-pull-requests/

**Comment by alsoijw** [comment]
[I create IDE setting in my fork.](https://github.com/Valama/valama/pull/224)
