### ISSUE TITLE
How to build a project written in Valama

### ISSUE THREAD

**Issue by alsoijw** [Valama/valama#221]
How to build a project written in Valama on the computer where not installed Valama? I choose plain build system. What command to type?

**Comment by LSenf** [comment]
The 'plain' backend is just valama calling valac directly; if you want to build without valama, you can use the cmake backend

**Comment by alsoijw** [comment]
```bash
$ find
.
./src
./src/main.vala
./build
./build/src=+main.vala
./vapi
./vapi/config.vapi
./first.vlp
```
Why you need a file ./build/src=+main.vala?

**Comment by alsoijw** [comment]
Anybody knows?

**Comment by LSenf** [comment]
Just to clarify, are you using valama or valamang? How did you create this project?

**Comment by LSenf** [comment]
Closing until further details are provided

**Comment by alsoijw** [comment]
@LSenf I am using valama. I select Create project, after that type of project, and path to it, dependence. After that valama asking me about choose buildsystem. I select plain.
