### ISSUE TITLE
Bake build system support

### ISSUE THREAD

**Issue by desiderantes** [Valama/valama#226]
[Bake](https://launchpad.net/bake) is an easy-to-use build system with great vala support. It would be great if Valama had support for this build system.

**Comment by LSenf** [comment]
Sounds interesting; This could be supported in valamang, but I don't have time for more than the cmake  and valama backends.
If you are interested in implementing a bake backend, I am happy to answer any questions :)

**Comment by LSenf** [comment]
I'll close this for now due to lack of feedback.
