### ISSUE TITLE
valamang

### ISSUE THREAD

**Issue by alsoijw** [Valama/valama#227]
I build branch valamang. I run it, and select new project.
```
alsoijw@debian:~/valama/build$ ./cmaketest 

** (cmaketest:15213): CRITICAL **: file /home/alsoijw/valama/build/src/ProjectTemplates/TemplateProvider.c: line 1016: uncaught error: Нет такого файла или каталога (g-io-error-quark, 1)

** (cmaketest:15213): CRITICAL **: ui_template_selector_template_construct: assertion 'provider != NULL' failed

(cmaketest:15213): GLib-GObject-CRITICAL **: g_object_ref_sink: assertion 'G_IS_OBJECT (object)' failed

(cmaketest:15213): Gtk-CRITICAL **: gtk_container_add: assertion 'GTK_IS_WIDGET (widget)' failed
Ошибка сегментирования
alsoijw@debian:~/valama/build$
```
"Ошибка сегментирования" is translating as Segmentation fault

**Comment by LSenf** [comment]
I think you have to 'make install' to get to the template selector.
Once you are there, the only functional template is plain vala (the others still need to be updated to the new project file format)

**Comment by inizan-yannick** [comment]
yes, this bug is due to old template. Please wait until @LSenf update valamang branch ;)

**Comment by alsoijw** [comment]
After reinstalling it works.
