### ISSUE TITLE
My impressions of valama

### ISSUE THREAD

**Issue by darkoverlordofdata** [Valama/valama#238]
Just so you know what I'm comparing valama to:

I'm trying to port a several thousand line game+framework to vala. I've already ported it from java to typescript and csharp. I used WebStorm, and VisualStudio Code for that,

I've gotten about 1/4 of the way in with valama and I'm giving up in favor of SublimeText. It is hard to refactor or debug/troubleshoot in valama.

The primary reason I'm not continuing with valama is that when it crashes, I lose code. I wish it had a save button, I would still use valama if it had a save buttonl.

wish list
* auto close for braces & brackets
* and auto indent on code blocks
* search & replace
* ability to rename and delete files in project view
* lines numbers - valac error have line numbers
* toggle comments for trouble shooting
* copy resources to build folder as part of build process

**Comment by LSenf** [comment]
Thank you for the feedback! Unfortunately, neither @Lasall nor me had enough time recently to work on valama...
Most of these things should be relatively easy to solve, some may already be available in gtksourceview and we just don't use these features yet.
I'm happy for every contribution, especially to valamang!

**Comment by darkoverlordofdata** [comment]
And I ended up droping vala anyway. The total dependency on GObject for language features ended up being a deal breaker for me.
